### ISSUE TITLE
submitAllRight uses submitAllLeft setting

### ISSUE THREAD

**Issue by tanj** [crlcu/multiselect#40] opened 2016-02-24 15:42 UTC
https://github.com/crlcu/multiselect/blob/master/js/multiselect.js#L65

Line 65 reads:
submitAllRight:     settings.submitAllRight !== undefined ? settings.submitAllLeft : true,

Should read:
submitAllRight:     settings.submitAllRight !== undefined ? settings.submitAllRight : true,

**Comment by crlcu** [comment] 2016-02-26 08:40
Hi @tanj 
Thanks for telling me about this issue.
A fix has pushed and the issue is now fixed.

**Closed by crlcu** 2016-02-26 08:40 UTC
Labels: bug
